name: Publish docs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate docs folder
        run: |
          echo "Listing docs/ folder"
          ls -la docs || true

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
